### PR TITLE
Fix usbmuxd socket connection issue for iOS >= 17.0

### PR DESCRIPTION
**Pull request by hyhcrh**
iPadOS within the specific range are also included.

See in [this comment](https://github.com/fritzlb/iOS17-JIT-WIN/issues/35#issuecomment-2053609437)

### CODE REVIEW

**Comment by fritzlb** [comment]
Thanks for the contribution, I really appreciate it! ☺️

I‘ll have to check if mounting developer images using the tunnel works by now, in my testing a few weeks back it didn’t (at least not reliably). Also this would in theory eliminate the need for iTunes which is known to cause issues with the drivers on some systems. 
While we can probably make this another command line option (or maybe even as an automatic fallback) I‘m not too sure about using —rsd as default

**Comment by hyhcrh** [comment]
Thanks for your reply, and it does let me think twice about this PR.
According to pymobiledevice3’s instructions, “—rsd” option is for devices whose system version is above 17.0.
So it is plausible to make this option as an automatic fallback. 
I have done in [this commit](https://github.com/fritzlb/iOS17-JIT-WIN/pull/36/commits/6e8d321367890a54afe7d12dbadca80c8a39ef8a).

**Comment by fritzlb** [comment]
Thank you so much!
The code itself looks really good, but it seems like your IDE/text editor changed the line endings from CRLF (Windows) to LF (Unix). Is there any chance you could revert this as older windows 10 builds have issues with this?
Also this makes reviewing really hard, but nothing a ´diff -u -w´ couldn't solve :)

**Comment by fritzlb** [comment]
Thank you so much for your help improving this project :)

**Comment by hyhcrh** [comment]
I managed to solve the ending problem, in a violent way, though. 😂
I'm still learning to use git, and thank you for pointing out the cause of the ending problem (becuase I don't know that) and helping me contribute to the project.

**Comment by fritzlb** [comment]
A violent way is better than no way :)
Yeah, that line ending issue is pretty old but still relevant. Idk if you remember, but on older windows versions some files would just open up as a single line in notepad, that‘s basically it.

**Pull request merged**
